// swift-tools-version: 6.0
import PackageDescription

// Uses the same production files and synthetic tests as Xcode without an App host.
// The Xcode project remains authoritative for the application and distribution.
let package = Package(
    name: "TargetDomain",
    platforms: [.macOS(.v15)],
    products: [.library(name: "TargetDomain", targets: ["Target"])],
    dependencies: [.package(url: "https://github.com/jpsim/Yams.git", exact: "6.2.2")],
    targets: [
        .target(name: "TargetCore", path: "TargetCore"),
        .target(name: "Target", dependencies: ["TargetCore", .product(name: "Yams", package: "Yams")],
                path: "Target", exclude: [
                    "Profile/WorldMapArtwork.swift",
                    "Profile/ProfileWorkspaceDetailView.swift",
                    "Profile/ProfileSubscriptionViews.swift",
                    "Profile/ProfileOverviewView.swift",
                    "Profile/ProfileLibraryViews.swift",
                    "Profile/ProfileConfigurationView.swift",
                    "Profile/PolicySelectorDetail.swift",
                    "Profile/PolicyMemberViews.swift",
                    "Profile/CountryRouteMap.swift",
                    "Profile/CountryRouteGrid.swift",
                    "Activity/RuntimeDiagnosticsView.swift",
                    "Assets.xcassets",
                    "Resources",
                    "Info.plist",
                    "TargetApp.swift",
                    "ContentView.swift",
                    "Activity/RuntimeActivityViews.swift",
                    "AppShell/AppShellView.swift",
                    "Dashboard/DashboardView.swift",
                    "MenuBar/MenuBarView.swift",
                    "Onboarding/OnboardingView.swift",
                    "Settings/SettingsView.swift",
                    "Settings/SMAppLoginItemManager.swift",
                    "Shared/TargetUI.swift",
                    "Updates",
                    "Profile/ProfileWorkspaceView.swift",
                    "Profile/ProfilePolicyWorkspaceView.swift",
                    "Profile/ProfileSiteRouteViews.swift",
                ],
                sources: [
                    "Activity/RuntimeConnectionPresentation.swift",
                    "Backend/BackendLifecycleModel.swift",
                    "Backend/BackendTypes.swift",
                    "Backend/EngineRuntimeOwnership.swift",
                    "Backend/MockBackend.swift",
                    "Backend/RuntimeActivity.swift",
                    "Backend/RuntimeControl.swift",
                    "Backend/SingBoxBackend.swift",
                    "Backend/TargetRuntimeOperations.swift",
                    "Backend/TargetSystemProxyOperations.swift",
                    "Service/HostNetworkSafety.swift",
                    "Service/SystemProxyController.swift",
                    "Service/TargetServiceClient.swift",
                    "Service/TargetServiceXPCProtocol.swift",
                    "Automation/TargetAutomationOperations.swift",
                    "Profile/ProfileModels.swift",
                    "Profile/SmartPolicyEngine.swift",
                    "Profile/SmartPolicyShadowOperations.swift",
                    "Profile/SmartContinuityOperations.swift",
                    "Profile/ProfileStore.swift",
                    "Profile/ProfileEncryptedStorage.swift",
                    "Profile/ProfileStorageCoordinator.swift",
                    "Profile/ProfileBackgroundWork.swift",
                    "Profile/ProfileTransfer.swift",
                    "Profile/ProfileSubscription.swift",
                    "Profile/SubscriptionIntake.swift",
                    "Profile/SingBoxConfigurationChecker.swift",
                    "Profile/ProfileRuntimeConfiguration.swift",
                    "Profile/ProfileViewModel.swift",
                    "Profile/ProfileWorkspaceInteraction.swift",
                    "Profile/PolicyWorkspacePresentation.swift",
                    "Profile/JSONLineNumberCalculation.swift",
                    "Profile/JSONSyntaxTokens.swift",
                    "Profile/JSONCodeEditor.swift",
                    "Profile/ProfileImportPanelResult.swift",
                    "Dashboard/DashboardPresentation.swift",
                    "MenuBar/MenuBarPresentation.swift",
                    "MenuBar/TargetMainWindowActivation.swift",
                    "AppShell/AppDestination.swift",
                    "AppShell/AppShellLayout.swift",
                    "Onboarding/OnboardingPresentation.swift",
                    "Settings/ApplicationPreferences.swift",
                    "Shared/TargetStatusLevel.swift",
                ]),
        .testTarget(name: "TargetDomainTests", dependencies: ["Target", "TargetCore"], path: "TargetTests",
                    exclude: ["AppShellRoutingTests.swift", "TargetUpdateControllerTests.swift"],
                    sources: [
                    "DeepOptimizationTests.swift",
                    "SmartPolicyEngineTests.swift",
                    "SmartPolicyShadowTests.swift",
                    "SmartPolicyApplyTests.swift",
                    "SmartContinuityTests.swift",
                    "SmartContinuityApplyTests.swift",
                    "BackendArchitectureTests.swift",
                    "EngineLifecycleTests.swift",
                    "TargetRuntimeOperationsTests.swift",
                    "SystemProxyRecoveryAvailabilityTests.swift",
                    "ProfileStorePersistenceTests.swift",
                    "ProfileStoreRecoveryTests.swift",
                    "ProfilePolicyPersistenceTests.swift",
                    "ProfileSubscriptionTests.swift",
                    "ProfileImportTests.swift",
                    "ProfileExportTests.swift",
                    "ProfileViewModelTests.swift",
                    "ProfileWorkspaceInteractionTests.swift",
                    "JSONLineNumberCalculationTests.swift",
                    "ApplicationPreferencesTests.swift",
                    "MenuBarPresentationTests.swift",
                    "RuntimeControlTests.swift",
                    "AutomationControlPlaneTests.swift",
                    "DashboardPresentationTests.swift",
                    "TestSupport/ProfileTestSupport.swift",
                ])
    ],
    swiftLanguageModes: [.v5]
)
